### ISSUE TITLE
Private key passphrase to connect to compute instance

### ISSUE THREAD

**Issue by sylvinameliajohn** [oracle-devrel/terraform-oci-arch-redis#9]
![redis_query](https://user-images.githubusercontent.com/77334410/164702642-353d4c52-d4b6-43f5-9e25-fd1aa8907196.JPG)
Hi team,
I am able to successfully use the terraform code to provision redis, after creation I am trying to connect to the instance using the generated private key - but getting an error message as shown. Have provided 400 permissions for the file, can u guide me on what I may be missing?

**Comment by lfeldman** [comment]
@sylvinameliajohn I am assuming you have used Deploy Button and OCI Resource Manager has been used to automate the deployment. In that case, generated private key is wrongly formatted. Please use https://www.samltool.com/format_privatekey.php to format the key properly.

**Comment by sylvinameliajohn** [comment]
Amazing that worked! Thank you for the super quick response..
